-- Approved six-role website operations model.
-- Senior Pastor and Associate Pastor are job titles on the shared Pastor role.
INSERT INTO roles (code, name, description) VALUES
  ('system_admin', 'System Administrator', 'Manages accounts, roles, security, integrations and system activity.'),
  ('pastor', 'Pastor', 'Pastoral oversight, public content leadership and sensitive prayer access.'),
  ('core_leader', 'Core Leader', 'Pastor-equivalent website operations access for selected highly trusted leaders.'),
  ('content_publisher', 'Content Publisher', 'Creates, approves, publishes and archives public content.'),
  ('content_editor', 'Content Editor', 'Creates and submits public content for approval.'),
  ('prayer_warrior', 'Prayer Warrior', 'Works only with permitted team prayer requests and pastoral escalation.');

INSERT INTO permissions (code, description, sensitivity) VALUES
  ('admin.access', 'Access the protected administration application.', 'standard'),
  ('staff.read', 'Read the staff directory.', 'personal'),
  ('staff.invite', 'Invite an individual staff account.', 'security'),
  ('staff.suspend', 'Suspend or disable a staff account.', 'security'),
  ('staff.roles.manage', 'Assign and revoke staff roles.', 'security'),
  ('roles.permissions.manage', 'Manage role permission mappings.', 'security'),
  ('settings.read', 'Read administrative settings.', 'security'),
  ('settings.manage', 'Change administrative settings.', 'security'),
  ('audit.activity.read', 'Read permitted administrative activity history.', 'security'),
  ('audit.security.read', 'Read security audit history.', 'security'),
  ('audit.prayer.read', 'Read prayer-domain audit history without prayer text.', 'prayer'),
  ('content.pages.manage', 'Manage public pages.', 'standard'),
  ('content.ministries.manage', 'Manage ministry content.', 'standard'),
  ('content.sermons.manage', 'Manage sermons.', 'standard'),
  ('content.series.manage', 'Manage sermon series.', 'standard'),
  ('content.speakers.manage', 'Manage sermon speakers.', 'standard'),
  ('content.schedule.manage', 'Manage schedule items.', 'standard'),
  ('content.announcements.manage', 'Manage announcements.', 'standard'),
  ('content.bulletins.manage', 'Manage bulletins.', 'standard'),
  ('content.media.manage', 'Manage approved media assets.', 'standard'),
  ('content.submit', 'Submit content for approval.', 'standard'),
  ('content.approve', 'Approve content inside an allowed content scope.', 'standard'),
  ('content.publish', 'Publish approved content inside an allowed content scope.', 'standard'),
  ('content.archive', 'Archive content inside an allowed content scope.', 'standard'),
  ('content.self_approve', 'Approve the account holder''s own work inside an allowed publishing scope.', 'security'),
  ('content.emergency_publish', 'Publish without the ordinary review path.', 'security'),
  ('contact.read', 'Read contact submissions.', 'personal'),
  ('contact.respond', 'Respond to contact submissions.', 'personal'),
  ('contact.assign', 'Assign contact submissions.', 'personal'),
  ('contact.export', 'Export contact submissions.', 'personal'),
  ('ministry_interest.read', 'Read ministry-interest submissions.', 'personal'),
  ('ministry_interest.respond', 'Respond to ministry-interest submissions.', 'personal'),
  ('ministry_interest.assign', 'Assign ministry-interest submissions.', 'personal'),
  ('ministry_interest.export', 'Export ministry-interest submissions.', 'personal'),
  ('prayer.read_team', 'Read prayer-team requests.', 'prayer'),
  ('prayer.read_pastoral', 'Read pastoral-only prayer requests.', 'prayer'),
  ('prayer.update_team', 'Update prayer-team requests.', 'prayer'),
  ('prayer.update_pastoral', 'Update pastoral-only prayer requests.', 'prayer'),
  ('prayer.assign', 'Assign prayer requests.', 'prayer'),
  ('prayer.contact.read', 'Read consented prayer contact information when allowed.', 'prayer'),
  ('prayer.escalate', 'Escalate a prayer request to pastoral leadership.', 'prayer'),
  ('prayer.close', 'Close an allowed prayer request.', 'prayer'),
  ('prayer.export', 'Export prayer requests.', 'prayer'),
  ('reports.content.read', 'Read permitted content reports.', 'standard'),
  ('reports.engagement.read', 'Read engagement reports.', 'personal'),
  ('reports.system.read', 'Read system health and usage reports.', 'security'),
  ('integrations.status.read', 'Read masked integration status.', 'security'),
  ('integrations.manage', 'Manage integration configuration.', 'security'),
  ('backups.status.read', 'Read backup status.', 'security'),
  ('data.retention.manage', 'Manage approved retention operations.', 'security');

WITH permission_grants(role_code, permission_code) AS (
  VALUES
    ('system_admin', 'admin.access'),
    ('system_admin', 'staff.read'),
    ('system_admin', 'staff.invite'),
    ('system_admin', 'staff.suspend'),
    ('system_admin', 'staff.roles.manage'),
    ('system_admin', 'roles.permissions.manage'),
    ('system_admin', 'settings.read'),
    ('system_admin', 'settings.manage'),
    ('system_admin', 'audit.activity.read'),
    ('system_admin', 'audit.security.read'),
    ('system_admin', 'reports.system.read'),
    ('system_admin', 'integrations.status.read'),
    ('system_admin', 'integrations.manage'),
    ('system_admin', 'backups.status.read'),

    ('pastor', 'admin.access'),
    ('pastor', 'staff.read'),
    ('pastor', 'settings.read'),
    ('pastor', 'audit.activity.read'),
    ('pastor', 'audit.prayer.read'),
    ('pastor', 'content.pages.manage'),
    ('pastor', 'content.ministries.manage'),
    ('pastor', 'content.sermons.manage'),
    ('pastor', 'content.series.manage'),
    ('pastor', 'content.speakers.manage'),
    ('pastor', 'content.schedule.manage'),
    ('pastor', 'content.announcements.manage'),
    ('pastor', 'content.bulletins.manage'),
    ('pastor', 'content.media.manage'),
    ('pastor', 'content.submit'),
    ('pastor', 'content.approve'),
    ('pastor', 'content.publish'),
    ('pastor', 'content.archive'),
    ('pastor', 'contact.read'),
    ('pastor', 'contact.respond'),
    ('pastor', 'contact.assign'),
    ('pastor', 'ministry_interest.read'),
    ('pastor', 'ministry_interest.respond'),
    ('pastor', 'ministry_interest.assign'),
    ('pastor', 'prayer.read_team'),
    ('pastor', 'prayer.read_pastoral'),
    ('pastor', 'prayer.update_team'),
    ('pastor', 'prayer.update_pastoral'),
    ('pastor', 'prayer.assign'),
    ('pastor', 'prayer.contact.read'),
    ('pastor', 'prayer.escalate'),
    ('pastor', 'prayer.close'),
    ('pastor', 'reports.content.read'),
    ('pastor', 'reports.engagement.read'),
    ('pastor', 'reports.system.read'),

    ('content_publisher', 'admin.access'),
    ('content_publisher', 'content.sermons.manage'),
    ('content_publisher', 'content.series.manage'),
    ('content_publisher', 'content.speakers.manage'),
    ('content_publisher', 'content.schedule.manage'),
    ('content_publisher', 'content.announcements.manage'),
    ('content_publisher', 'content.bulletins.manage'),
    ('content_publisher', 'content.media.manage'),
    ('content_publisher', 'content.submit'),
    ('content_publisher', 'content.approve'),
    ('content_publisher', 'content.publish'),
    ('content_publisher', 'content.archive'),
    ('content_publisher', 'content.self_approve'),
    ('content_publisher', 'reports.content.read'),

    ('content_editor', 'admin.access'),
    ('content_editor', 'content.sermons.manage'),
    ('content_editor', 'content.series.manage'),
    ('content_editor', 'content.speakers.manage'),
    ('content_editor', 'content.schedule.manage'),
    ('content_editor', 'content.announcements.manage'),
    ('content_editor', 'content.bulletins.manage'),
    ('content_editor', 'content.media.manage'),
    ('content_editor', 'content.submit'),
    ('content_editor', 'reports.content.read'),

    ('prayer_warrior', 'admin.access'),
    ('prayer_warrior', 'prayer.read_team'),
    ('prayer_warrior', 'prayer.update_team'),
    ('prayer_warrior', 'prayer.contact.read'),
    ('prayer_warrior', 'prayer.escalate'),
    ('prayer_warrior', 'prayer.close')
)
INSERT INTO role_permissions (role_code, permission_code)
SELECT grant_row.role_code, grant_row.permission_code
FROM permission_grants AS grant_row
JOIN roles AS role ON role.code = grant_row.role_code
JOIN permissions AS permission ON permission.code = grant_row.permission_code;

-- Core Leaders intentionally mirror the Pastor role. Assignment remains an
-- elevated System Administrator action and requires a recorded reason.
INSERT INTO role_permissions (role_code, permission_code)
SELECT 'core_leader', permission_code
FROM role_permissions
WHERE role_code = 'pastor';
