-- Approved system roles
INSERT INTO roles (code, name, description) VALUES
  ('system_admin', 'System Administrator', 'Manages accounts, roles, security, integrations and system activity.'),
  ('senior_pastor', 'Senior Pastor', 'Senior church leadership access, including approved sensitive decisions.'),
  ('associate_pastor', 'Associate Pastor', 'Pastoral and operational leadership access.'),
  ('leader', 'Leader', 'Associate-Pastor-equivalent day-to-day operational access.'),
  ('core_leader', 'Core Leader', 'System-Administrator-assigned Senior-Pastor-equivalent access for selected trusted Leaders.'),
  ('multimedia_head', 'Multimedia Head', 'Multimedia scope management, approval, publishing and self-approval.'),
  ('multimedia_team', 'Multimedia Team', 'Creates and submits multimedia-scope content.'),
  ('bulletin_head', 'Bulletin Head', 'Bulletin scope management, approval, publishing and self-approval.'),
  ('bulletin_team', 'Bulletin Team', 'Creates and submits bulletin-scope content.'),
  ('treasurer', 'Treasurer', 'Manages detailed giving records, reconciliation, receipts and reports.'),
  ('prayer_warrior', 'Prayer Warrior', 'Works with permitted prayer requests and pastoral escalation.');

-- Approved granular permissions
INSERT INTO permissions (code, description, sensitivity) VALUES
  ('admin.access', 'Access the protected administration application.', 'standard'),
  ('staff.read', 'Read the staff directory.', 'personal'),
  ('staff.invite', 'Invite an individual staff account.', 'security'),
  ('staff.suspend', 'Suspend or disable a staff account.', 'security'),
  ('staff.roles.manage', 'Assign and revoke staff roles.', 'security'),
  ('roles.permissions.manage', 'Manage role permission mappings.', 'security'),
  ('settings.read', 'Read administrative settings.', 'security'),
  ('settings.manage', 'Change administrative settings.', 'security'),
  ('audit.activity.read', 'Read permitted administrative activity history.', 'security'),
  ('audit.security.read', 'Read security audit history.', 'security'),
  ('audit.prayer.read', 'Read prayer-domain audit history without prayer text.', 'prayer'),
  ('audit.finance.read', 'Read finance-domain audit history.', 'financial'),
  ('content.pages.manage', 'Manage public pages.', 'standard'),
  ('content.ministries.manage', 'Manage ministry content.', 'standard'),
  ('content.sermons.manage', 'Manage sermons.', 'standard'),
  ('content.series.manage', 'Manage sermon series.', 'standard'),
  ('content.speakers.manage', 'Manage sermon speakers.', 'standard'),
  ('content.schedule.manage', 'Manage schedule items.', 'standard'),
  ('content.announcements.manage', 'Manage announcements.', 'standard'),
  ('content.bulletins.manage', 'Manage bulletins.', 'standard'),
  ('content.media.manage', 'Manage approved media assets.', 'standard'),
  ('content.submit', 'Submit content for approval.', 'standard'),
  ('content.approve', 'Approve content inside an allowed content scope.', 'standard'),
  ('content.publish', 'Publish approved content inside an allowed content scope.', 'standard'),
  ('content.archive', 'Archive content inside an allowed content scope.', 'standard'),
  ('content.self_approve', 'Approve the account holder''s own work inside an allowed Head scope.', 'security'),
  ('content.emergency_publish', 'Publish without the ordinary review path.', 'security'),
  ('contact.read', 'Read contact submissions.', 'personal'),
  ('contact.respond', 'Respond to contact submissions.', 'personal'),
  ('contact.assign', 'Assign contact submissions.', 'personal'),
  ('contact.export', 'Export contact submissions.', 'personal'),
  ('ministry_interest.read', 'Read ministry-interest submissions.', 'personal'),
  ('ministry_interest.respond', 'Respond to ministry-interest submissions.', 'personal'),
  ('ministry_interest.assign', 'Assign ministry-interest submissions.', 'personal'),
  ('ministry_interest.export', 'Export ministry-interest submissions.', 'personal'),
  ('prayer.read_team', 'Read prayer-team requests.', 'prayer'),
  ('prayer.read_pastoral', 'Read pastoral-only prayer requests.', 'prayer'),
  ('prayer.update_team', 'Update prayer-team requests.', 'prayer'),
  ('prayer.update_pastoral', 'Update pastoral-only prayer requests.', 'prayer'),
  ('prayer.assign', 'Assign prayer requests.', 'prayer'),
  ('prayer.contact.read', 'Read consented prayer contact information when allowed.', 'prayer'),
  ('prayer.escalate', 'Escalate a prayer request to pastoral leadership.', 'prayer'),
  ('prayer.close', 'Close an allowed prayer request.', 'prayer'),
  ('prayer.export', 'Export prayer requests.', 'prayer'),
  ('giving.summary.read', 'Read aggregate giving summaries.', 'financial'),
  ('giving.details.read', 'Read transaction-level giving records.', 'financial'),
  ('giving.contributors.read', 'Read contributor identity.', 'financial'),
  ('giving.online.reconcile', 'Reconcile online giving.', 'financial'),
  ('giving.offline.create', 'Create offline giving entries.', 'financial'),
  ('giving.offline.verify', 'Verify another staff member''s offline entry.', 'financial'),
  ('giving.adjustment.request', 'Request a contribution adjustment.', 'financial'),
  ('giving.adjustment.approve', 'Approve another staff member''s adjustment.', 'financial'),
  ('giving.refund.request', 'Request a refund.', 'financial'),
  ('giving.refund.approve', 'Approve another staff member''s refund.', 'financial'),
  ('giving.receipt.manage', 'Manage receipt requests.', 'financial'),
  ('giving.categories.manage', 'Manage giving categories.', 'financial'),
  ('giving.export', 'Export permitted giving records.', 'financial'),
  ('reports.content.read', 'Read permitted content reports.', 'standard'),
  ('reports.engagement.read', 'Read engagement reports.', 'personal'),
  ('reports.system.read', 'Read system health and usage reports.', 'security'),
  ('integrations.status.read', 'Read masked integration status.', 'security'),
  ('integrations.manage', 'Manage integration configuration.', 'security'),
  ('backups.status.read', 'Read backup status.', 'security'),
  ('data.retention.manage', 'Manage approved retention operations.', 'security');

WITH permission_grants(role_code, permission_code) AS (
  VALUES
    ('system_admin', 'admin.access'),
    ('system_admin', 'staff.read'),
    ('system_admin', 'staff.invite'),
    ('system_admin', 'staff.suspend'),
    ('system_admin', 'staff.roles.manage'),
    ('system_admin', 'roles.permissions.manage'),
    ('system_admin', 'settings.read'),
    ('system_admin', 'settings.manage'),
    ('system_admin', 'audit.activity.read'),
    ('system_admin', 'audit.security.read'),
    ('system_admin', 'reports.system.read'),
    ('system_admin', 'integrations.status.read'),
    ('system_admin', 'integrations.manage'),
    ('system_admin', 'backups.status.read'),

    ('senior_pastor', 'admin.access'),
    ('senior_pastor', 'staff.read'),
    ('senior_pastor', 'settings.read'),
    ('senior_pastor', 'audit.activity.read'),
    ('senior_pastor', 'audit.prayer.read'),
    ('senior_pastor', 'audit.finance.read'),
    ('senior_pastor', 'content.pages.manage'),
    ('senior_pastor', 'content.ministries.manage'),
    ('senior_pastor', 'content.sermons.manage'),
    ('senior_pastor', 'content.series.manage'),
    ('senior_pastor', 'content.speakers.manage'),
    ('senior_pastor', 'content.schedule.manage'),
    ('senior_pastor', 'content.announcements.manage'),
    ('senior_pastor', 'content.bulletins.manage'),
    ('senior_pastor', 'content.media.manage'),
    ('senior_pastor', 'content.submit'),
    ('senior_pastor', 'content.approve'),
    ('senior_pastor', 'content.publish'),
    ('senior_pastor', 'content.archive'),
    ('senior_pastor', 'contact.read'),
    ('senior_pastor', 'contact.respond'),
    ('senior_pastor', 'contact.assign'),
    ('senior_pastor', 'ministry_interest.read'),
    ('senior_pastor', 'ministry_interest.respond'),
    ('senior_pastor', 'ministry_interest.assign'),
    ('senior_pastor', 'prayer.read_team'),
    ('senior_pastor', 'prayer.read_pastoral'),
    ('senior_pastor', 'prayer.update_team'),
    ('senior_pastor', 'prayer.update_pastoral'),
    ('senior_pastor', 'prayer.assign'),
    ('senior_pastor', 'prayer.contact.read'),
    ('senior_pastor', 'prayer.escalate'),
    ('senior_pastor', 'prayer.close'),
    ('senior_pastor', 'giving.summary.read'),
    ('senior_pastor', 'giving.adjustment.approve'),
    ('senior_pastor', 'giving.refund.approve'),
    ('senior_pastor', 'reports.content.read'),
    ('senior_pastor', 'reports.engagement.read'),
    ('senior_pastor', 'reports.system.read'),
    ('senior_pastor', 'integrations.status.read'),
    ('senior_pastor', 'backups.status.read'),

    ('associate_pastor', 'admin.access'),
    ('associate_pastor', 'staff.read'),
    ('associate_pastor', 'settings.read'),
    ('associate_pastor', 'audit.activity.read'),
    ('associate_pastor', 'audit.prayer.read'),
    ('associate_pastor', 'content.pages.manage'),
    ('associate_pastor', 'content.ministries.manage'),
    ('associate_pastor', 'content.sermons.manage'),
    ('associate_pastor', 'content.series.manage'),
    ('associate_pastor', 'content.speakers.manage'),
    ('associate_pastor', 'content.schedule.manage'),
    ('associate_pastor', 'content.announcements.manage'),
    ('associate_pastor', 'content.bulletins.manage'),
    ('associate_pastor', 'content.media.manage'),
    ('associate_pastor', 'content.submit'),
    ('associate_pastor', 'content.approve'),
    ('associate_pastor', 'content.publish'),
    ('associate_pastor', 'content.archive'),
    ('associate_pastor', 'contact.read'),
    ('associate_pastor', 'contact.respond'),
    ('associate_pastor', 'contact.assign'),
    ('associate_pastor', 'ministry_interest.read'),
    ('associate_pastor', 'ministry_interest.respond'),
    ('associate_pastor', 'ministry_interest.assign'),
    ('associate_pastor', 'prayer.read_team'),
    ('associate_pastor', 'prayer.read_pastoral'),
    ('associate_pastor', 'prayer.update_team'),
    ('associate_pastor', 'prayer.update_pastoral'),
    ('associate_pastor', 'prayer.assign'),
    ('associate_pastor', 'prayer.contact.read'),
    ('associate_pastor', 'prayer.escalate'),
    ('associate_pastor', 'prayer.close'),
    ('associate_pastor', 'giving.summary.read'),
    ('associate_pastor', 'reports.content.read'),
    ('associate_pastor', 'reports.engagement.read'),
    ('associate_pastor', 'reports.system.read'),

    ('multimedia_head', 'admin.access'),
    ('multimedia_head', 'content.sermons.manage'),
    ('multimedia_head', 'content.series.manage'),
    ('multimedia_head', 'content.speakers.manage'),
    ('multimedia_head', 'content.schedule.manage'),
    ('multimedia_head', 'content.announcements.manage'),
    ('multimedia_head', 'content.media.manage'),
    ('multimedia_head', 'content.submit'),
    ('multimedia_head', 'content.approve'),
    ('multimedia_head', 'content.publish'),
    ('multimedia_head', 'content.archive'),
    ('multimedia_head', 'content.self_approve'),
    ('multimedia_head', 'reports.content.read'),

    ('multimedia_team', 'admin.access'),
    ('multimedia_team', 'content.sermons.manage'),
    ('multimedia_team', 'content.series.manage'),
    ('multimedia_team', 'content.speakers.manage'),
    ('multimedia_team', 'content.schedule.manage'),
    ('multimedia_team', 'content.announcements.manage'),
    ('multimedia_team', 'content.media.manage'),
    ('multimedia_team', 'content.submit'),
    ('multimedia_team', 'reports.content.read'),

    ('bulletin_head', 'admin.access'),
    ('bulletin_head', 'content.schedule.manage'),
    ('bulletin_head', 'content.announcements.manage'),
    ('bulletin_head', 'content.bulletins.manage'),
    ('bulletin_head', 'content.media.manage'),
    ('bulletin_head', 'content.submit'),
    ('bulletin_head', 'content.approve'),
    ('bulletin_head', 'content.publish'),
    ('bulletin_head', 'content.archive'),
    ('bulletin_head', 'content.self_approve'),
    ('bulletin_head', 'reports.content.read'),

    ('bulletin_team', 'admin.access'),
    ('bulletin_team', 'content.schedule.manage'),
    ('bulletin_team', 'content.announcements.manage'),
    ('bulletin_team', 'content.bulletins.manage'),
    ('bulletin_team', 'content.media.manage'),
    ('bulletin_team', 'content.submit'),
    ('bulletin_team', 'reports.content.read'),

    ('treasurer', 'admin.access'),
    ('treasurer', 'audit.finance.read'),
    ('treasurer', 'giving.summary.read'),
    ('treasurer', 'giving.details.read'),
    ('treasurer', 'giving.contributors.read'),
    ('treasurer', 'giving.online.reconcile'),
    ('treasurer', 'giving.offline.create'),
    ('treasurer', 'giving.offline.verify'),
    ('treasurer', 'giving.adjustment.request'),
    ('treasurer', 'giving.refund.request'),
    ('treasurer', 'giving.receipt.manage'),
    ('treasurer', 'giving.export'),

    ('prayer_warrior', 'admin.access'),
    ('prayer_warrior', 'prayer.read_team'),
    ('prayer_warrior', 'prayer.update_team'),
    ('prayer_warrior', 'prayer.contact.read'),
    ('prayer_warrior', 'prayer.escalate')
)
INSERT INTO role_permissions (role_code, permission_code)
SELECT grant_row.role_code, grant_row.permission_code
FROM permission_grants AS grant_row
JOIN roles AS role ON role.code = grant_row.role_code
JOIN permissions AS permission ON permission.code = grant_row.permission_code;

-- Leaders intentionally mirror Associate Pastor permissions.
INSERT INTO role_permissions (role_code, permission_code)
SELECT 'leader', permission_code
FROM role_permissions
WHERE role_code = 'associate_pastor';

-- Core Leaders intentionally mirror Senior Pastor permissions.
INSERT INTO role_permissions (role_code, permission_code)
SELECT 'core_leader', permission_code
FROM role_permissions
WHERE role_code = 'senior_pastor';
